require 'cocoapods'
require 'cocoapods_plugin'
require 'cocoapods-catalyst-support'
require 'cocoapods-catalyst-support/command'
require 'cocoapods-catalyst-support/command/catalyst/init'
require 'cocoapods-catalyst-support/command/catalyst/validate'
require 'cocoapods-catalyst-support/command/catalyst/run'
